---
- name: Unconfigure VSTS agent
  command: "sudo -u {{ vsts_agent_user }} ./config.sh remove --unattended --auth PAT --token {{ vsts_accesstoken }}"
  args:
    chdir: "{{ vsts_agent_folder }}"
  no_log: true
  tags: unconfig

- name: Include tasks to configure VSTS agent
  include_tasks: "../common/configure.yml"
  when: dryrun is not defined
  tags: config

- name: Configure VSTS agent
  command: "sudo -u {{ vsts_agent_user }} {{ vsts_install_command }}"
  args:
    chdir: "{{ vsts_agent_folder }}"
    creates: "{{ vsts_agent_folder }}/.agent"
  no_log: true
  notify: restart vsts-agent systemd service
